import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import locationsRouter from "./locations";
import monitoringRouter from "./monitoring";
import alertsRouter from "./alerts";
import industriesRouter from "./industries";
import aiRouter from "./ai";
import reportsRouter from "./reports";
import citizensRouter from "./citizens";
const router: IRouter = Router();
router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", authRouter);
router.use("/locations", locationsRouter);
router.use("/monitoring", monitoringRouter);
router.use("/alerts", alertsRouter);
router.use("/industries", industriesRouter);
router.use("/ai", aiRouter);
router.use("/reports", reportsRouter);
router.use("/citizens", citizensRouter);
export default router;